### PR TITLE
a few build fix

### PR DESCRIPTION
**Pull request by miniupnp**
the empty "m4" directory is not checked out from the git repository :)

### CODE REVIEW

**Comment by miniupnp** [comment]
So update *your* documentation : 
```
$ ./autogen.sh 
[...]
type './configure' to configure libpomp.
type 'make' to compile libpomp.
type 'make install' to install libpomp.

```

**Comment by ncarrier** [comment]
ok ok ^^, a patch to the documentation should be welcome.

PS: I'm not the author of the code

2016-02-23 16:58 GMT+01:00 Thomas BERNARD <notifications@github.com>:

**Comment by ymorgan** [comment]
The m4 directory and the ax_cxx_compile_stdcxx_11.m4 is actually missing in the repository....
my mistake.
The INSTALL doc is the 'standard' autotools one and the build in source tree is accepted. the .git ignore should then be updated.

**Comment by miniupnp** [comment]
@ncarrier building in the source tree or not is a matter of religious belief. So I think you should allow it, even if bad according to you own belief

**Comment by ymorgan** [comment]
I pushed 2 commits with the missing m4 dir and files and the updated .gitignore (from your suggestion and some other stuff when examples are also compiled).

**Comment by miniupnp** [comment]
@ymorgan : I also added a .travis.yml
commit 6d25763b65dd2cefd899087699aefcfa425614ec
see https://travis-ci.org/

**Pull request closed without merging**
