### PR TITLE
[DEV] Get rid of libfutils dependency.

### PR DESCRIPTION
**Pull request by claudemr**
- It was just using some list facilities which
  could be implemented manually, like in the
  rest of libpomp.

### CODE REVIEW

**Comment by acharruel** [comment]
Hi there,
I did not really review this one but I have the same issue when trying to build libpomp dependant stuff on another build system (ie. x86 with meson).
Sounds a good idea to remove this dependancy, or maybe add a generic build support for libfutils (autotools, meson, standard Makefile or whatever...) :)

**Comment by claudemr** [comment]
Hello!
I'll probably submit another patch for that particular pull-request and use macros. My code is a bit hard to reason about.

Lately I've been working on using libpomp on Win32 (for conga), hence those patches.

(btw, I've just messaged you on linked-in) :)

**Comment by ymorgan** [comment]
There is a issue when passing the unit test on linux. There is a segfault in the test checking removal during an idle (pomp_test_loop.c 525)

**Comment by claudemr** [comment]
Ok, I'm onto it.

Do you have some instructions to pass the test. How do I get TARGET_TEST enabled?

**Comment by claudemr** [comment]
Hello,
I fixed the problem. It now passes the tests successfully.

**Comment by claudemr** [comment]
Thanks ! :)

**Pull request merged**
